// <auto-generated />
using System;
using FilmLister.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FilmLister.Persistence.Migrations
{
    [DbContext(typeof(FilmListerContext))]
    partial class FilmListerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FilmLister.Persistence.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageUrl");

                    b.Property<string>("ImdbId");

                    b.Property<string>("Name");

                    b.Property<int>("TmdbId");

                    b.HasKey("Id");

                    b.ToTable("Films");
                });

            modelBuilder.Entity("FilmLister.Persistence.FilmListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FilmId");

                    b.Property<int?>("FilmListTemplateId");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("FilmListTemplateId");

                    b.ToTable("FilmListItems");
                });

            modelBuilder.Entity("FilmLister.Persistence.FilmListTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("FilmListTemplates");
                });

            modelBuilder.Entity("FilmLister.Persistence.OrderedFilm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FilmId");

                    b.Property<int?>("OrderedListId");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("OrderedListId");

                    b.ToTable("OrderedFilms");
                });

            modelBuilder.Entity("FilmLister.Persistence.OrderedFilmRankItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("GreaterRankedFilmId");

                    b.Property<int?>("LesserRankedFilmId");

                    b.HasKey("Id");

                    b.HasIndex("GreaterRankedFilmId");

                    b.HasIndex("LesserRankedFilmId");

                    b.ToTable("OrderedFilmRankItems");
                });

            modelBuilder.Entity("FilmLister.Persistence.OrderedList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Completed");

                    b.Property<int?>("FilmListTemplateId");

                    b.HasKey("Id");

                    b.HasIndex("FilmListTemplateId");

                    b.ToTable("OrderedLists");
                });

            modelBuilder.Entity("FilmLister.Persistence.FilmListItem", b =>
                {
                    b.HasOne("FilmLister.Persistence.Film", "Film")
                        .WithMany("FilmListItems")
                        .HasForeignKey("FilmId");

                    b.HasOne("FilmLister.Persistence.FilmListTemplate", "FilmListTemplate")
                        .WithMany("FilmListItems")
                        .HasForeignKey("FilmListTemplateId");
                });

            modelBuilder.Entity("FilmLister.Persistence.OrderedFilm", b =>
                {
                    b.HasOne("FilmLister.Persistence.Film", "Film")
                        .WithMany()
                        .HasForeignKey("FilmId");

                    b.HasOne("FilmLister.Persistence.OrderedList")
                        .WithMany("OrderedFilms")
                        .HasForeignKey("OrderedListId");
                });

            modelBuilder.Entity("FilmLister.Persistence.OrderedFilmRankItem", b =>
                {
                    b.HasOne("FilmLister.Persistence.OrderedFilm", "GreaterRankedFilm")
                        .WithMany("GreaterRankedFilmItems")
                        .HasForeignKey("GreaterRankedFilmId");

                    b.HasOne("FilmLister.Persistence.OrderedFilm", "LesserRankedFilm")
                        .WithMany("LesserRankedFilmItems")
                        .HasForeignKey("LesserRankedFilmId");
                });

            modelBuilder.Entity("FilmLister.Persistence.OrderedList", b =>
                {
                    b.HasOne("FilmLister.Persistence.FilmListTemplate", "FilmListTemplate")
                        .WithMany()
                        .HasForeignKey("FilmListTemplateId");
                });
#pragma warning restore 612, 618
        }
    }
}
